// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_mysql

var TableNames = struct {
	Jets           string
	Languages      string
	PilotLanguages string
	Pilots         string
}{
	Jets:           "jets",
	Languages:      "languages",
	PilotLanguages: "pilot_languages",
	Pilots:         "pilots",
}
